baseURL = "http://cadex.xyz/"
theme = "nav-community-v2"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = true

twitter_username = "cadex"
enableRobotsTXT = true

[taxonomies]
  npip_category = "npip_categories"
  notice_category = "notice_categories"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[Languages]
    [Languages.en]
        title = "Cadex - An Easy To Use Decentralized Cryptocurrency"
        weight = 1
        languageName = "English"


# Main Menu English
[[Languages.en.menu.main]]
    name = "Explore"
    title = "Explore"
    weight = 3
    identifier = "explore"
    [[Languages.en.menu.main]]
        name = "Roadmap"
        title = "Roadmap"
        weight = 3
        url = "/roadmap/"
        identifier = "roadmap"
        parent = "explore"
    [[Languages.en.menu.main]]
        name = "Block Explorer"
        title = "Block Explorer"
        weight = 4
        url = "http://cadex"
        identifier = "block-explorer"
        parent = "explore"

[[Languages.en.menu.main]]
    name = "News"
    title = "News"
    url="/notices/"
    weight = 4
    identifier = "news"
[[Languages.en.menu.main]]
    name = "Wallets"
    title = "Wallets"
    weight = 40
    identifier = "wallets"
    url = "https://github.com/cadexproject/cadex"

# Main Menu Spanish

[[Languages.es.menu.main]]

