---
pages:
- merchants/index.md
- information/index.md
- get-involved/index.md
- about-this-website/index.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
